"use client";

import { useState, useEffect, useRef } from "react";
import * as THREE from "three";
import { Shell, Header, QuizPanel, mono, Card } from "./LabUI";
import { createScene, attachOrbitDrag } from "./three/SceneKit";

const QUIZ = [
  { q: "Slicing a (double) cone with a plane PERPENDICULAR to the axis produces:",
    options: ["Hyperbola", "Parabola", "Circle", "Triangle"], correct: 2 },
  { q: "Tilting the plane LESS than the cone's slant gives:",
    options: ["A circle", "An ellipse (a closed loop, slightly stretched)", "A parabola", "A hyperbola"], correct: 1 },
  { q: "When the plane is PARALLEL to the slant of the cone, the section is:",
    options: ["A circle", "An ellipse", "A parabola (open curve)", "A line"], correct: 2 },
  { q: "If the plane is steeper than the slant and cuts BOTH halves of the double cone, the section is:",
    options: ["Two ellipses", "Two parabolas", "A hyperbola (two-branch curve)", "A circle"], correct: 2 },
];

export default function ConicSectionsLab() {
  const mountRef = useRef(null);
  const sceneRef = useRef({});
  const [tilt, setTilt] = useState(0);  // plane tilt angle (radians from horizontal)
  const [answers, setAnswers] = useState({});
  const [submitted, setSubmitted] = useState(false);
  const tiltRef = useRef(0);

  useEffect(() => {
    const mount = mountRef.current;
    if (!mount) return;
    const { scene, camera, renderer, dispose } = createScene(mount, {
      background: 0xfdfbf3,
      camera: { x: 1.3, y: 1.1, z: 1.5, lookY: 0.0 },
    });
    // ground plane (subtle grid)
    const grid = new THREE.GridHelper(2, 20, 0x1a1f2e, 0x1a1f2e);
    grid.material.opacity = 0.15; grid.material.transparent = true;
    grid.position.y = -0.6;
    scene.add(grid);

    // double cone (two cones tip-to-tip)
    const coneMat = new THREE.MeshPhysicalMaterial({
      color: 0xc2185b, transparent: true, opacity: 0.32,
      transmission: 0.4, roughness: 0.2, side: THREE.DoubleSide, ior: 1.3,
    });
    const cone1 = new THREE.Mesh(new THREE.ConeGeometry(0.5, 0.6, 48, 1, true), coneMat);
    cone1.position.y = 0.3;
    scene.add(cone1);
    const cone2 = new THREE.Mesh(new THREE.ConeGeometry(0.5, 0.6, 48, 1, true), coneMat);
    cone2.rotation.x = Math.PI;
    cone2.position.y = -0.3;
    scene.add(cone2);

    // cutting plane
    const planeMat = new THREE.MeshPhysicalMaterial({
      color: 0x1a8af0, transparent: true, opacity: 0.25,
      transmission: 0.35, roughness: 0.1, side: THREE.DoubleSide,
    });
    const plane = new THREE.Mesh(new THREE.PlaneGeometry(1.6, 1.6, 1, 1), planeMat);
    plane.rotation.x = -Math.PI / 2;
    scene.add(plane);

    // intersection curve — generated by raycasting points along the plane onto the cone
    const curveMat = new THREE.LineBasicMaterial({ color: 0xc2185b, linewidth: 3 });
    let curveLine = null;

    // central axis line (cone axis)
    const axisLine = new THREE.Mesh(new THREE.CylinderGeometry(0.003, 0.003, 1.2, 8), new THREE.MeshStandardMaterial({ color: 0x1a1f2e }));
    scene.add(axisLine);

    sceneRef.current = { scene, camera, renderer, dispose, plane, getCurveLine: () => curveLine, setCurveLine: (l) => { curveLine = l; } };

    const detach = attachOrbitDrag(camera, renderer.domElement, { lookY: 0 });

    // Compute the conic section curve at every frame as tilt changes
    function updateCurve(tiltDeg) {
      // Cone: axis along y, half-angle α with tan α = 0.5 / 0.6 ≈ 0.833 → α ≈ 39.8°
      // Plane: tilted around z-axis by `tiltDeg` from horizontal.
      // Parameterise points on the cone surface and check if they're on the plane (within tolerance).
      // Simpler approach: parameterise points on the plane (u, v) and check if they're on the cone.
      // Cone in cylindrical: r = (0.5 / 0.6) * |y| → |y| × tan α
      const slantSlope = 0.5 / 0.6; // r per |y|
      const t = tiltDeg;
      const cosT = Math.cos(t), sinT = Math.sin(t);
      // plane basis vectors
      const u = new THREE.Vector3(1, 0, 0); // along z=0
      const v = new THREE.Vector3(0, sinT, cosT); // tilted

      const pts = [];
      // Walk a 2-D grid on the plane and find sign-changes of (r_cone - r_point)
      const N = 360;
      const SAMPLES = 250;
      for (let i = 0; i < N; i++) {
        const angle = (i / N) * Math.PI * 2;
        // shoot a ray from plane origin at angle (cos a × u + sin a × v)
        const dir = new THREE.Vector3()
          .copy(u).multiplyScalar(Math.cos(angle))
          .add(new THREE.Vector3().copy(v).multiplyScalar(Math.sin(angle)));
        // step out along ray and find where it intersects cone surface
        let lastSign = null;
        for (let s = 0; s < SAMPLES; s++) {
          const dist = (s / SAMPLES) * 1.5;
          const p = new THREE.Vector3().copy(dir).multiplyScalar(dist);
          const rPt = Math.sqrt(p.x * p.x + p.z * p.z);
          const rCone = Math.abs(p.y) * slantSlope;
          const diff = rPt - rCone;
          if (lastSign != null && Math.sign(diff) !== Math.sign(lastSign)) {
            pts.push(p.clone());
            break;
          }
          lastSign = diff;
        }
      }

      // Replace curve
      if (curveLine) {
        scene.remove(curveLine);
        curveLine.geometry.dispose();
      }
      if (pts.length > 0) {
        const geom = new THREE.BufferGeometry().setFromPoints([...pts, pts[0]]);
        const line = new THREE.LineLoop(geom, curveMat);
        scene.add(line);
        curveLine = line;
      }
    }

    let raf;
    let lastTilt = -1;
    const animate = () => {
      const t = tiltRef.current;
      plane.rotation.x = -Math.PI / 2 + t;
      if (Math.abs(t - lastTilt) > 0.005) {
        updateCurve(t);
        lastTilt = t;
      }
      renderer.render(scene, camera);
      raf = requestAnimationFrame(animate);
    };
    raf = requestAnimationFrame(animate);

    return () => { cancelAnimationFrame(raf); detach(); dispose(); };
  }, []);

  useEffect(() => { tiltRef.current = tilt; }, [tilt]);

  // Classify section
  // Cone half-angle α ≈ 39.8° = 0.694 rad
  const alpha = Math.atan(0.5 / 0.6);
  const t = Math.abs(tilt);
  let kind;
  if (t < 0.02) kind = "Circle";
  else if (t < alpha - 0.02) kind = "Ellipse";
  else if (Math.abs(t - alpha) < 0.04) kind = "Parabola";
  else kind = "Hyperbola";

  const score = QUIZ.reduce((acc, q, i) => (answers[i] === q.correct ? acc + 1 : acc), 0);

  return (
    <Shell back="/maths" backLabel="Back to Maths" topic="Maths · Geometry · Conic sections">
      <Header
        title="Conic"
        accent="sections"
        blurb="Slice a double cone with a plane. As you tilt the plane, the cross-section morphs through four classical curves — circle → ellipse → parabola → hyperbola — each defined by how the plane's angle compares to the cone's slant."
      />

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        <div className="lg:col-span-7">
          <div ref={mountRef} className="relative mb-4"
            style={{ aspectRatio: "1/1", maxHeight: 500, backgroundColor: "#fdfbf3", border: "1px solid rgba(26,31,46,0.2)", overflow: "hidden" }} />

          <div className="p-4 mb-3" style={{ backgroundColor: "rgba(26,31,46,0.04)", border: "1px solid rgba(26,31,46,0.18)" }}>
            <div className="text-[10px] uppercase opacity-60 mb-1" style={{ fontFamily: mono, letterSpacing: "0.18em" }}>plane tilt</div>
            <input type="range" min="0" max={Math.PI / 2 - 0.05} step="0.01" value={tilt} onChange={(e) => setTilt(parseFloat(e.target.value))} className="w-full" />
            <div className="text-sm" style={{ fontFamily: mono }}>tilt = {(tilt * 180 / Math.PI).toFixed(0)}° · section: <span style={{ color: "#c2185b", fontWeight: 600 }}>{kind}</span></div>
          </div>
        </div>

        <div className="lg:col-span-5">
          <Card label="The four conics">
            <div className="text-xs space-y-2">
              <div><span style={{ fontFamily: mono, color: "#c2185b", fontWeight: 600 }}>Circle</span> — plane perpendicular to axis (tilt = 0)</div>
              <div><span style={{ fontFamily: mono, color: "#c2185b", fontWeight: 600 }}>Ellipse</span> — tilt &lt; slant angle of cone</div>
              <div><span style={{ fontFamily: mono, color: "#c2185b", fontWeight: 600 }}>Parabola</span> — tilt EQUALS slant angle</div>
              <div><span style={{ fontFamily: mono, color: "#c2185b", fontWeight: 600 }}>Hyperbola</span> — tilt steeper than slant; plane cuts both cone halves</div>
            </div>
            <div className="text-xs opacity-75 mt-3 leading-snug">
              All four arise as solutions to one general quadratic Ax² + Bxy + Cy² + … = 0; the conics are the unifying family.
            </div>
          </Card>
          <div className="mt-4">
            <QuizPanel quiz={QUIZ} answers={answers} setAnswers={setAnswers} submitted={submitted} setSubmitted={setSubmitted} score={score} />
          </div>
        </div>
      </div>
    </Shell>
  );
}
